site_name: IdpyOIDC Architecture Documentation

nav:
        - Introduction: intro.md
        - Message: message.md
        - Client: client/index.md
        - Server: server.md
        - Persistent storage: persistence.md
        - Code Reference:
          - Client: client_code.md

markdown_extensions:
    - toc:
        permalink: true

theme:
        name: material

plugins:
    - search
    - git-revision-date
    - mkdocstrings