site_name: IdpyOIDC Architecture Documentation

nav:
        - Introduction: intro.md
        - Message: message.md
        - Client: client.md
        - Server: server.md
        - Persistent storage: persistence.md

markdown_extensions:
    - toc:
        permalink: true

theme:
        name: material

plugins:
    - search
    - git-revision-date